name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      ProductClientId: ${{ secrets.PRODUCTCLIENTID }}
      ProductClientSecret: ${{ secrets.PRODUCTCLIENTSECRET }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.300

    - name: Restore dependencies
      run: dotnet restore Aspose.Cells.Cloud.SDK/Aspose.Cells.Cloud.SDK.csproj

    - name: Build
      run: dotnet build --no-restore -p:Configuration=Release

    - name: Run Examples
      run: |
        cd examples
        dotnet test Example_QuickStart.csproj --verbosity normal
